apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: beautiful-frog-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: beautiful-frog-go 
  name: beautiful-frog-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: beautiful-frog-go 
